### ISSUE TITLE
Undefined symbols for architecture arm64 on mac m1 chip

### ISSUE THREAD

**Issue by moisko** [Castaglia/MacOSX-authbind#9]
when i try to build the project, this is what i get

MacOSX-authbind git:(master) make
cc -DMAJOR_VER='""' -DMINOR_VER='""' -DLIBAUTHBIND='"/usr/local/lib/authbind/libauthbind.dylib"' -DHELPER='"/usr/local/lib/authbind/helper"' -DCONFIGDIR='"/etc/authbind"' -D_GNU_SOURCE -DPRELOAD_VAR='"DYLD_INSERT_LIBRARIES"' -arch x86_64 -g -O2 -D_REENTRANT -Wall -Wwrite-strings -Wpointer-arith -Wimplicit -Wnested-externs -Wmissing-prototypes -Wstrict-prototypes -flat_namespace -c authbind.c
clang: warning: argument unused during compilation: '-flat_namespace' [-Wunused-command-line-argument]
cc -o authbind authbind.o
ld: warning: ignoring file authbind.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [authbind] Error 1

**Comment by IvanNikolchov** [comment]
Modify the Makefile and change `ARCH`  to:

`ARCH=-arch arm64`

`make clean` and try again.

**Comment by moisko** [comment]
yes, it works as described above.
thanks for sharing

**Comment by tvardy** [comment]
Would be worth putting in the main README.md... I've searched for a moment to find this info...
I think I'll prepare a PR for that...
